dir:
  name: { maxLen: 20, style: lower_case }
  size: { maxEntries: 20 }
file:
  name: { maxLen: 20, style: lower_case }
  size: { maxLines: 300, testMaxLines: 600, maxLine: 100 }

pkg: { maxLen: 20, style: lower_case }

func:
  name:       { maxLen: 30, style: camelCase }
  size:       { maxParams: 5, maxResults: 3, maxStatements: 30 }
funcInTest:
  name:       { maxLen: 30, style: camelCase }
  size:       { maxParams: 5, maxResults: 3, maxStatements: 30 }

struct:
  fieldName: { maxLen: 30, Style: camelCase }
  size:      { maxFields: 100 }

type:      { maxLen: 30, style: camelCase }
const:     { maxLen: 30, style: camelCase }
var:       { maxLen: 40, style: camelCase }

localConst: { maxLen: 20, style: lowerCamelCase }
localType:  { maxLen: 20, style: lowerCamelCase }
localVar:   { maxLen: 30, style: lowerCamelCase }

label: { maxLen: 20, style: lowerCamelCase }

