language: go
go:
  - "1.10"
install:
  - go get github.com/mattn/goveralls
script:
  # - go test -v -coverprofile=coverage.out . ./problems ./rules/...
  - go test -v -coverprofile=coverage.out  ./rules/objects/names/...
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
